services:
    xray:
        image: teddysun/xray
        restart: always
        volumes:
            - ./config:/etc/xray
            - ./logs:/var/log/xray
        depends_on:
          - wgcf
        network_mode: "service:wgcf"

    wgcf:
        image: neilpang/wgcf-docker:latest
        volumes:
            - ./wgcf:/wgcf
            - /lib/modules:/lib/modules
        privileged: true
        sysctls:
            net.ipv6.conf.all.disable_ipv6: 0
        cap_add:
          - NET_ADMIN
        restart: unless-stopped
        ports:
          - "<ports:ports>"